#!/bin/bash

count=0

while read -r old new name
do
    if [[ ! $new =~ ^[0]+$ ]]; then
        (( count+=1 ))
    fi
done

#silence silly warnings
old=$old
name=$name

if [ $count -gt 1 ]; then
    echo "Error: can only push one branch to build repository"
    exit 1
fi

if [ $count -eq 0 ]; then
    exit 0
fi

if [ -f "$PWD/.moz-building" ]; then
    echo "Error: existing $PWD/.moz-building lockfile indicates that a build is in process already"
    exit 1
fi

if [ -z "$BUILD_DIR" ]; then
    echo "Error: must set target build dir in \$BUILD_DIR"
    exit 1
fi

if [ -z "$BUILD_COMMAND" ]; then
    echo "Error: must set build command in \$BUILD_COMMAND"
    exit 1
fi

case "$BUILD_DIR" in
    (/*) if ! pathchk -- "$BUILD_DIR"; then
             echo "Error: must set \$BUILD_DIR to a valid path"
             exit 1
         fi
         ;;
    (*) echo "Error: must set \$BUILD_DIR to absolute path"
        exit 1
        ;;
esac

touch "$PWD/.context-switch-building"
